# Generated by Django 4.1.7 on 2023-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.URLField()),
                ('timeframe', models.IntegerField()),
                ('json_file', models.URLField()),
            ],
        ),
    ]
